name: build
on:
  push:
    branches: ["main"]
    tags: ["*"]
  pull_request:
jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: python -m pip install --upgrade pip wheel
      - run: pip install tox
      - run: tox -elint
  release:
    needs: [lint]
    name: PyPI release
    if: startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: python -m pip install --upgrade pip wheel
      - run: pip install twine
      - run: python setup.py sdist bdist_wheel
      - run: twine upload -u __token__ -p ${{ secrets.PYPI_API_TOKEN }} dist/*
