name: build
on:
  push:
    branches: ["main"]
    tags: ["*"]
  pull_request:
jobs:
  tests:
    name: ${{ matrix.name }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - {name: '3.9', python: '3.9', tox: py39}
          - {name: '3.10', python: '3.10', tox: py310}
          - {name: '3.11', python: '3.11', tox: py311}
          - {name: '3.12', python: '3.12', tox: py312}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
      - name: Run test
        run: |
          python -m pip install tox
          python -m tox -e${{ matrix.tox }}
      - name: Upload coverage
        uses: codecov/codecov-action@v3
  build:
    name: Build package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install pypa/build
        run: python -m pip install build
      - name: Build a binary wheel and a source tarball
        run: python -m build
      - name: Install twine
        run: python -m pip install twine
      - name: Check build
        run: python -m twine check --strict dist/*
      - name: Store the distribution packages
        uses: actions/upload-artifact@v4
        with:
          name: python-package-distributions
          path: dist/
  # this duplicates pre-commit.ci, so only run it on tags
  # it guarantees that linting is passing prior to a release
  lint-pre-release:
    name: lint
    if: startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - run: python -m pip install tox
      - run: python -m tox -elint
  publish-to-pypi:
    name: PyPI release
    if: startsWith(github.ref, 'refs/tags/')
    needs: [build, tests, lint-pre-release]
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/bemserver-ui
    permissions:
      id-token: write
    steps:
      - name: Download all the dists
        uses: actions/download-artifact@v4
        with:
          name: python-package-distributions
          path: dist/
      - name: Publish distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
